"""empty message

Revision ID: bcdde153f6ae
Revises: 
Create Date: 2024-03-28 15:39:43.054046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcdde153f6ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('support')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('complejidad', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('trabajador_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajador.id'], name='support_trabajador_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='support_pkey')
    )
    # ### end Alembic commands ###
