"""empty message

Revision ID: c1ae9cc22f5d
Revises: bcdde153f6ae
Create Date: 2024-03-29 15:01:09.188714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1ae9cc22f5d'
down_revision = 'bcdde153f6ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('complejidad', sa.Integer(), nullable=False),
    sa.Column('trabajador_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('support')
    # ### end Alembic commands ###
